#!/data/data/com.termux/files/usr/bin/bash
#script to invoke jar with correct params
#	location of android.jar :- required for
#	java.lang package.
	
	droidjar=android.jar

#	package name of jar

	package_jar="sun.tools.jar.Main"

#	call jdktools with appropriate params
jdktools $package_jar $@
