#!/data/data/com.termux/files/usr/bin/bash
#script to invoke javah with correct params
#	location of android.jar :- required for
#	java.lang package.
	
	droidjar=android.jar

#	package name of javah

	package_javah="com.sun.tools.javah.Main"

#	call jdktools with appropriate params
jdktools \
		$package_javah \
		-bootclasspath $droidjar \
		-classpath $PWD $@
