#!/data/data/com.termux/files/usr/bin/bash
#script to invoke javac with correct params
#	location of android.jar :- required for
#	java.lang package.
	
	droidjar=$my/files/data/android.jar

#	package name of javac

	package_javac="com.sun.tools.javac.Main"

#	call jdktools with appropriate params
jdktools \
		$package_javac \
		-bootclasspath $droidjar $@
